# Generated by Django 3.2 on 2021-04-17 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=250, verbose_name='Наименование категории')),
                ('Description', models.TextField(verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Оповещение',
                'verbose_name_plural': 'Оповещения',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, verbose_name='Имя')),
                ('Surname', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('Phone', models.TextField(blank=True, verbose_name='Телефон')),
                ('Email', models.TextField(verbose_name='Эл.почта')),
                ('Occupation', models.TextField(blank=True, verbose_name='Вид спорта')),
                ('SocialNetworks', models.TextField(blank=True, verbose_name='Соц.Сети')),
                ('City', models.TextField(verbose_name='Город')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
